# image: node:10
image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: registry.anvita.com.vn
  CI_DOCKER_COMPOSE_SERVICE_NAME: web-client
  CI_REGISTRY_IMAGE: anfast-avf/$CI_DOCKER_COMPOSE_SERVICE_NAME
  DEPLOYMENT_SERVER_SSH_PORT: 19451
  DEPLOYMENT_SERVER_HOST: swarm-master.anvami.vn
  DEV_SERVER_HOST: dev.giaodichnongsan.vn
  DOCKER_STACK_NAME: anfast-avf

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - lint
  - test
#   - build
#   - deploy
  - push-registry-dev
  - deploy-dev
  - push-registry-prd
  - deploy-prd

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

push-registry-dev:
  stage: push-registry-dev
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f Dockerfile.dev .
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY/$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY/$CI_REGISTRY_IMAGE:latest"
  tags:
    - docker
  only:
    - master
    
deploy-dev:
  stage: deploy-dev
  image: alpine
  only:
    - master
  environment: dev

  before_script:
    - apk --no-cache add ca-certificates 
    - apk add --no-cache rsync
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$RSA_PRIVATE_KEY_DEV" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - ssh antrade-cd@$DEV_SERVER_HOST "docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD' $CI_REGISTRY;  docker pull $CI_REGISTRY/$CI_REGISTRY_IMAGE:latest; docker service update --force '${DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_NAME}'"


push-registry-prd:
  stage: push-registry-prd
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f Dockerfile.prd .
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY/$CI_REGISTRY_IMAGE:stable"
    - docker push "$CI_REGISTRY/$CI_REGISTRY_IMAGE:stable"
  tags:
    - docker
  only:
    - production
    
deploy-prd:
  stage: deploy-prd
  image: alpine
  only:
    - production
  environment: production

  before_script:
    - apk --no-cache add ca-certificates 
    - apk add --no-cache rsync
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$RSA_PRIVATE_KEY_BE_PRD_DO" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - ssh -p $DEPLOYMENT_SERVER_SSH_PORT antrade-cd@$DEPLOYMENT_SERVER_HOST "docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD' $CI_REGISTRY;  docker pull $CI_REGISTRY/$CI_REGISTRY_IMAGE:stable; docker service update --force '${DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_NAME}'"


